name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: JDK17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Maven build
        run: mvn build

      - name: Maven Test
        run: mvn test

      - name: Docker image
        run: docker build -t bensnellgrove/jenkins-testing:${{ github.sha }} .

      - name: Dockerhub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker push
        run: docker push bensnellgrove/jenkins-testing:${{ github.sha }}
